### ISSUE TITLE
Remove dist/ files from the repo

### ISSUE THREAD

**Issue by caffo** [caffo/org-minimal-html-theme#17]
@rafaelrinaldi Wouldn't you think it would be a good choice?

**Comment by rafaelrinaldi** [comment]
@caffo Yup! I initially added them to SCM because I thought you wanted it. Anyone who wants the assets, just have to clone the repo and run the build command anyways.

**Comment by gabrielalmeida** [comment]
Although it's normally best practice to not send `dist` to `vcs`, I see an use case where someone may just want to export an org file and have theme styles/js applied, without having to build nor customize anything.

As sample setup files states:
```
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://dl.dropboxusercontent.com/u/8178/org-minimal/bundle.min.css"/>
#+HTML_HEAD: <script src="https://dl.dropboxusercontent.com/u/8178/org-minimal/bundle.min.js" type="text/javascript" ></script>
```

Should be enough to someone willing to have a stylized export. Instead of relying on Dropbox, something like rawgit could be used to serve latest available version with correct `Content-Type` headers:

```
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href=" https://rawgit.com/caffo/org-minimal-html-theme/master/dist/bundle.min.css
"/>
#+HTML_HEAD: <script src=" https://rawgit.com/caffo/org-minimal-html-theme/master/dist/bundle.min.js
" type="text/javascript" ></script>
```

This way people will always be able to use latest available theme version just by appending two lines to their org file. It's even possible to generate multiple builds, with different options on `theme.json` and get all of them to be served this way.

Just thinking about keeping it as easy as possible for anyone willing to try this.

**Comment by caffo** [comment]
@gabrielalmeida I'm going to publish some pre-compiled files in a CDN soon. Removing `/dist/` files for now. :)
